[package]
name = "dbus-dummy"
version = "0.1.0"
edition = "2021"
description = "Dummy package to bypass rust feature check"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = []
vendored = []
